<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ChangelogFile>$(SolutionDir)/CHANGELOG.md</ChangelogFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Elmish.Commands.fs" />
    <Compile Include="Elmish.Subscriptions.fs" />
    <Compile Include="Elmish.Time.fs" />
    <Compile Include="Elmish.Rendering.fs" />
    <Compile Include="Elmish.ProgramTypes.fs" />
    <Compile Include="Elmish.Runtime.fs" />
    <Compile Include="Camera.fs" />
    <Compile Include="Input.fs" />
    <Compile Include="Layout/Grid2D.fs" />
    <Compile Include="Layout/Layout.fs" />
    <Compile Include="Layout/Layered.fs" />
    <Compile Include="Layout/Platformer.fs" />
    <Compile Include="InputMapper.fs" />
    <Compile Include="Culling.fs" />
    <Compile Include="Assets.fs" />
    <Compile Include="Render.Shared.fs" />
    <Compile Include="BillboardBatch.fs" />
    <Compile Include="LineBatch.fs" />
    <Compile Include="Graphics2D.fs" />
    <Compile Include="Animation.fs" />
    <Compile Include="Sprite3DTypes.fs" />
    <Compile Include="SpriteQuadBatch.fs" />
    <Compile Include="QuadBatch.fs" />
    <Compile Include="Rendering3D/Lighting.fs" />
    <Compile Include="Rendering3D/Types.fs" />
    <Compile Include="Rendering3D/Config.fs" />
    <Compile Include="Rendering3D/SpriteQuadBatch.fs" />
    <Compile Include="Rendering3D/LineBatch.fs" />
    <Compile Include="Rendering3D/Pipeline.fs" />
    <Compile Include="Rendering3D/View.fs" />
    <Compile Include="Rendering3D/Program.fs" />
    <Compile Include="Graphics3D.fs" />
    <Compile Include="System.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mibo.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    <PackageReference Include="JDeck" Version="1.0.0" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ionide.KeepAChangelog.Tasks" Version="0.3.1" PrivateAssets="all" />
  </ItemGroup>
</Project>
