<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PipelineSample</RootNamespace>
    <IsPackable>false</IsPackable>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="Platform.fs" />
    <Compile Include="Movement.fs" />
    <Compile Include="Physics.fs" />
    <Compile Include="Rotation.fs" />
    <Compile Include="Player.fs" />
    <Compile Include="Grid.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Mibo/Mibo.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content/Content.mgcb" />
  </ItemGroup>
</Project>
