<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ChangelogFile>$(SolutionDir)/CHANGELOG.md</ChangelogFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fsi" />
    <Compile Include="Types.fs" />
    <Compile Include="Drawable.fsi" />
    <Compile Include="Drawable.fs" />
    <Compile Include="Bindings.fsi" />
    <Compile Include="Bindings.fs" />
    <Compile Include="Config.fsi" />
    <Compile Include="Config.fs" />
    <Compile Include="PipelineInternals.fsi" />
    <Compile Include="PipelineInternals.fs" />
    <Compile Include="Pipeline.fsi" />
    <Compile Include="Pipeline.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    <PackageReference Include="JDeck" Version="1.0.0" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.*" PrivateAssets="all" />
    <PackageReference Include="Ionide.KeepAChangelog.Tasks" Version="0.3.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mibo\Mibo.fsproj" />
  </ItemGroup>

</Project>