<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
    <CodesignKey>iPhone Developer</CodesignKey>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyGame.Core\MyGame.Core.fsproj" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
    <PackageReference Include="MonoGame.Framework.iOS" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\MyGame.Core\Content\Content.mgcb">
      <Link>Content\Pomo.mgcb</Link>
    </MonoGameContentReference>
  </ItemGroup>
</Project>
