<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.companyname.MyGame</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyGame.Core\MyGame.Core.fsproj" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MyGameActivity.fs" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\MyGame.Core\Content\Content.mgcb">
      <Link>Content\Pomo.mgcb</Link>
    </MonoGameContentReference>
  </ItemGroup>
</Project>
